# DeckForge fish completion
# Autogenerated by deckforge completion fish

function __deckforge_themes
    echo "academic-crimson\tDeep Peruvian crimson with midnight navy"
    echo "cyber-dark\tDeep OLED canvas with neon emerald and purple"
    echo "neon-cyber\tGlowing cyan and electric magenta accents"
    echo "terminal-green\tMatrix green monospace developer terminal"
    echo "swiss-minimal\tHigh-contrast monochrome with stark Bauhaus red"
    echo "paper-ink\tWarm cream with rich charcoal ink and crimson"
    echo "vintage-editorial\tWarm cream with distinctive Fraunces serif"
    echo "electric-studio\tHigh-contrast dark canvas with sharp electric royal blue"
    echo "creative-voltage\tElectric cobalt with vivid neon yellow callouts"
    echo "bold-signal\tVibrant orange focal card on dark gradient canvas"
    echo "notebook-tabs\tWarm cream paper sheets with pastel tabs"
    echo "pastel-geometry\tSoft pastel sky background with violet pill tags"
    echo "dark-botanical\tCharcoal noir canvas with warm gold and terracotta"
    echo "split-pastel\tTwo-color peach and lavender panels with mint"
end

function __deckforge_subcommands
    echo "tui\tLaunch interactive terminal user interface"
    echo "new\tInitialize a new presentation (alias: init, create)"
    echo "build\tCompile presentation to standalone 1080p HTML"
    echo "serve\tStart local web server with live reload watcher"
    echo "export\tHeadless export to PDF via Chromium"
    echo "list\tList themes and discovered presentations"
    echo "slide\tManage slide operations (add)"
    echo "theme\tTheme management (list, set, create, seed, clone)"
    echo "book\tManage living Development Book (status, log, audit)"
    echo "agent\tAI-native headless JSON CLI for LLMs"
    echo "mcp\tLaunch stdio Model Context Protocol server"
    echo "completion\tGenerate shell autocompletions (fish)"
    echo "version\tPrint DeckForge version and runtime information"
end

complete -c deckforge -f

# Main subcommands
complete -c deckforge -n "__fish_use_subcommand" -a "(__deckforge_subcommands)"

# Flags for root/build/serve/new
complete -c deckforge -l help -s h -d "Display help information"
complete -c deckforge -l version -s v -d "Print version"
complete -c deckforge -l path -d "Target destination directory" -r
complete -c deckforge -l theme -d "Select presentation theme" -x -a "(__deckforge_themes)"
complete -c deckforge -l slides -d "Number of slides for scaffolding"
complete -c deckforge -l port -d "HTTP port for serve"
complete -c deckforge -l watch -d "Enable live file watcher"
complete -c deckforge -l pdf -d "Export as PDF format"

# Theme subcommands
complete -c deckforge -n "__fish_seen_subcommand_from theme" -a "list set create seed clone"
complete -c deckforge -n "__fish_seen_subcommand_from theme; and __fish_seen_subcommand_from set" -a "(__deckforge_themes)"
complete -c deckforge -n "__fish_seen_subcommand_from theme; and __fish_seen_subcommand_from create seed clone" -l base -s b -x -a "(__deckforge_themes)"
complete -c deckforge -n "__fish_seen_subcommand_from theme; and __fish_seen_subcommand_from create seed clone" -l global -s g -d "Scope theme to ~/.config/deckforge/themes/"
complete -c deckforge -n "__fish_seen_subcommand_from theme; and __fish_seen_subcommand_from create seed clone" -l scss -d "Scaffold modular .scss stylesheets instead of .css"

# Slide subcommands
complete -c deckforge -n "__fish_seen_subcommand_from slide" -a "add"

# Book subcommands
complete -c deckforge -n "__fish_seen_subcommand_from book" -a "status log audit"

# Agent subcommands
complete -c deckforge -n "__fish_seen_subcommand_from agent" -a "catalog styling-guide deck-info deck-meta deck-create theme-list theme-set theme-create slide-get slide-set slide-reorder tokens-audit tokens-fix component-insert export-skill"

# Completion subcommands
complete -c deckforge -n "__fish_seen_subcommand_from completion" -a "fish"
complete -c deckforge -n "__fish_seen_subcommand_from completion" -l install -s i -d "Install completion script to ~/.config/fish/completions/"
